### ISSUE TITLE
[BUG] - Unable to see configuration for Self Hosted UniFi Controllers (#798) nor stats

### ISSUE THREAD

**Issue by hibikipr** [linuxserver/Heimdall-Apps#802]
**Describe the bug**
The new toggle button for self-hosted UniFi configuration does not show up in the heimdall configuration page. The live stats don't show up either, even when the connection test is successful. See Screenshots.  

I have a Unifi Cloud Gateway Ultra 

**To Reproduce**
Configure UniFi as an application.

**Expected behavior**

**Screenshots**
![Screenshot 2024-11-16 at 5 20 50 PM](https://github.com/user-attachments/assets/c6513349-5691-41c0-9b25-1654fe9423f0)
![Screenshot 2024-11-16 at 5 24 35 PM](https://github.com/user-attachments/assets/00e783c7-3cdf-4362-8ae9-03f99d96dc41)

**Version info (please complete the following information):**
 - Heimdall: 2.6.3
 - Docker: 27.3.1 (API: 1.47)
- UniFi Network: 8.6.9
- UniFi OS 4.0.20

**Additional context**

Results from 
curl -k -X GET -b cookie.txt https://192.168.3.1/proxy/network/api/s/default/stat/health
{"meta":{"rc":"ok"},"data":[{"subsystem":"wlan","num_user":49,"num_guest":0,"num_iot":12,"tx_bytes-r":199070,"rx_bytes-r":344618,"status":"ok","num_ap":2,"num_adopted":2,"num_disabled":0,"num_disconnected":0,"num_pending":0},{"subsystem":"wan","num_gw":1,"num_adopted":1,"num_disconnected":0,"num_pending":0,"status":"ok","wan_ip":"XXX.XXX.XXX.XXX","gateways":["fxxx.xxx.x.xx.xx","XXX.XXX.XXX.XXX"],"netmask":"255.255.192.0","nameservers":[],"num_sta":58,"tx_bytes-r":290097,"rx_bytes-r":612271,"gw_mac":"XXX:XXX:XX:XX","gw_name":"CGU","gw_system-stats":{"cpu":"8.0","mem":"57.2","uptime":"636199"},"gw_version":"4.0.20.16882","isp_name":"XXX","isp_organization":"BHN-XXXX","uptime_stats":{"WAN":{"alerting_monitors":[{"availability":100.0,"latency_average":19,"target":"ping.ui.com","type":"icmp"},{"availability":100.0,"latency_average":101,"target":"1.1.1.1","type":"dns"},{"availability":100.0,"latency_average":100,"target":"8.8.8.8","type":"dns"}],"availability":100.0,"latency_average":20,"monitors":[{"availability":100.0,"latency_average":36,"target":"www.microsoft.com","type":"icmp"},{"availability":100.0,"latency_average":19,"target":"google.com","type":"icmp"},{"availability":100.0,"latency_average":21,"target":"1.1.1.1","type":"icmp"}],"time_period":86400,"uptime":203690}}},{"subsystem":"www","status":"ok","tx_bytes-r":290097,"rx_bytes-r":612271,"latency":24,"uptime":203706,"drops":2,"xput_up":37.0,"xput_down":534.0,"speedtest_status":"Success","speedtest_lastrun":1731754111,"speedtest_ping":17,"gw_mac":"9c:05:d6:6f:3f:0d"},{"subsystem":"lan","lan_ip":null,"status":"ok","num_user":9,"num_guest":0,"num_iot":1,"tx_bytes-r":1203695,"rx_bytes-r":10407,"num_sw":3,"num_adopted":3,"num_disconnected":0,"num_pending":0},{"subsystem":"vpn","status":"unknown"}]}

**Comment by hibikipr** [comment]
Here is the screenshot for UniFi in Heimdall
![Screenshot 2024-11-16 at 5 35 33 PM](https://github.com/user-attachments/assets/6dfd95de-62ae-4c34-9a1f-4202e7ba6937)

**Comment by hibikipr** [comment]
the following error message shows in the caravel logs under www/logs/laravel-2024-11-16.log

[2024-11-16 22:12:19] local.ERROR: cURL error 60: SSL certificate problem: self-signed certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://192.168.3.1/api/auth/login {"exception":"[object] (GuzzleHttp\\Exception\\RequestException(code: 0): cURL error 60: SSL certificate problem: self-signed certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://192.168.3.1/api/auth/login at /app/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211)
[stacktrace]
#0 /app/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\\Handler\\CurlFactory::createRejection()
#1 /app/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\\Handler\\CurlFactory::finishError()
#2 /app/www/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\\Handler\\CurlFactory::finish()
#3 /app/www/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke()
#4 /app/www/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#5 /app/www/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#6 /app/www/vendor/guzzlehttp/guzzle/src/Middleware.php(38): GuzzleHttp\\PrepareBodyMiddleware->__invoke()
#7 /app/www/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#8 /app/www/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\\RedirectMiddleware->__invoke()
#9 /app/www/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#10 /app/www/vendor/guzzlehttp/guzzle/src/Client.php(333): GuzzleHttp\\HandlerStack->__invoke()
#11 /app/www/vendor/guzzlehttp/guzzle/src/Client.php(169): GuzzleHttp\\Client->transfer()
#12 /app/www/vendor/guzzlehttp/guzzle/src/Client.php(189): GuzzleHttp\\Client->requestAsync()
#13 /app/www/app/SupportedApps.php(94): GuzzleHttp\\Client->request()
#14 /config/www/SupportedApps/UniFi/UniFi.php(35): App\\SupportedApps->execute()
#15 /app/www/app/Http/Controllers/ItemController.php(490): App\\SupportedApps\\UniFi\\UniFi->livestats()
#16 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\ItemController->getStats()
#17 /app/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#18 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#19 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#20 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#21 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#22 /app/www/app/Http/Middleware/CheckAllowed.php(42): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\CheckAllowed->handle()
#24 /app/www/app/Http/Controllers/Controller.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(165): App\\Http\\Controllers\\Controller->App\\Http\\Controllers\\{closure}()
#26 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#28 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#30 /app/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#32 /app/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /app/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#34 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#35 /app/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#37 /app/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#39 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#41 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#42 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#43 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#44 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#45 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#46 /app/www/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#48 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#50 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#51 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#53 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#54 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#56 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#58 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#60 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#61 /app/www/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle()
#62 {main}
"}

**Comment by hibikipr** [comment]
Setting "Skip TLS Verification" fix it for me.
